CREATE TABLE IF NOT EXISTS academy_courses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  stage VARCHAR(20) NOT NULL,
  title VARCHAR(140) NOT NULL,
  description TEXT,
  icon VARCHAR(20) DEFAULT '📚',
  sort_order INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS academy_lessons (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  course_id INT UNSIGNED NOT NULL,
  title VARCHAR(140) NOT NULL,
  content MEDIUMTEXT,
  video_url VARCHAR(255) NULL,
  sort_order INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS academy_progress (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  lesson_id INT UNSIGNED NOT NULL,
  completed_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS academy_badges (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  icon VARCHAR(20) DEFAULT '🏆',
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS academy_user_badges (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  badge_id INT UNSIGNED NOT NULL,
  earned_at DATETIME DEFAULT CURRENT_TIMESTAMP
);